### ISSUE TITLE
How should we handle errors and return specific responses ?

### ISSUE THREAD

**Issue by o-bo** [yrong/koa-neo4j#5]
For example : if I have a constraint on my user labels saying the email must be unique : how can I catch the error in my defineApi in order to return a 422 with a specific json : {email: "already exists"} ; for now I only get a 409 with the cypher message.

Same question for a check lifecycle method :  if I set a check method that validates a password with its confirmation, I would like to return a 422 with a json {confirmation: "does not match"} ; for now I only get a 409 with a message saying the check lifecycle hook did not pass.

**Comment by 2bigO** [comment]
Hi @o-bo 
You should be able to use context's `throw` as described in [koa's documentation](https://github.com/koajs/koa/blob/master/docs/api/context.md#ctxthrowstatus-msg-properties):

```javascript
app.defineAPI({
    check: (params, ctx) => {
        if (failureCondition)
            ctx.throw(422, 'confirmation does not match', {confirmation: "does not match"});
    }
});
```

Same for a preProcess lifecycle.

**Comment by o-bo** [comment]
Perfect. I also noticed that check can take a procedure ; so we could use it to fetch an already existing user with an email and throw an error in that case.

**Comment by 2bigO** [comment]
>  I also noticed that check can take a procedure

Yes. You can also use procedures as `preProcess`, `postProcess` and `postServe` lifecycles. Glad it helped.
