### ISSUE TITLE
koa-neo4j is placed for adoption

### ISSUE THREAD

**Issue by 2bigO** [yrong/koa-neo4j#8]
I invite anyone interested in future development of this project to take ownership of this repository and its `npm` package.
@mehdibalouchi
@farhoud
@yrong

**Comment by yrong** [comment]
@keyvan-m-sadeghi 
Is there anything new you want to add for this repo?  I may have a try if you do not have time.

**Comment by 2bigO** [comment]
Thanks @yrong, nothing special right now, will send pull requests if something came up.
I just tried to transfer to you, but it complains that [yrong/koa-neo4j](https://github.com/yrong/koa-neo4j) already exists:

<img width="960" alt="yrong" src="https://user-images.githubusercontent.com/1758649/53852636-c5ed1400-3f90-11e9-9b47-24f927aa62cf.png">

Could you please delete your fork so I can complete the transfer?

`npm` package is now yours:
<img width="960" alt="ronyang" src="https://user-images.githubusercontent.com/1758649/53852845-63e0de80-3f91-11e9-84f2-a16e7915e050.png">

**Comment by 2bigO** [comment]
@yrong I just sent you a request for transferring `koa-neo4j-starter-kit`:
<img width="960" alt="starter" src="https://user-images.githubusercontent.com/1758649/53853459-870c8d80-3f93-11e9-9f39-132df9db9a3b.png">

**Comment by yrong** [comment]
I've deleted the forked repo and you may try it again

**Comment by 2bigO** [comment]
@yrong Done. You just need to accept now, I believe you would receive two emails (one for `koa-neo4j`, another for `koa-neo4j-starter-kit`).

An starting issue could be fixing the failing [Travis builds](https://travis-ci.org/assister-ai/koa-neo4j).

Best of luck! Let me know if I could help with anything, anytime 🎉

**Comment by yrong** [comment]
@keyvan-m-sadeghi  I've fixed the building error and just add new issues if anything necessary.

**Comment by 2bigO** [comment]
Great, thanks @yrong.
